### ISSUE TITLE
Zipkin tracer server_url parsed as an empty string

### ISSUE THREAD

**Issue by nitedani** [ory/x#583]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/x/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/x/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I trouble setting up tracing in keto, kratos and oathkeeper, and I couldn't find a solution. I configured tracing in each of them, the same way.
In their respective configuration files, I added the following tracing configuration:
```
tracing:
  service_name: Ory Keto
  providers:
    zipkin:
      server_url: http://tempo:9411/api/v2/spans
  provider: zipkin
```
I confirmed that http://tempo:9411/api/v2/spans is able to receive zipkin spans, and that they show up in grafana. But the ory services seem not to pick up this url. For example, in the ory keto logs I can see the following:
```
09T13:10:12Z level=info msg=Zipkin tracer configured! Sending spans to  func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.451/logrusx/helper.go:118 audience=application service_name=Ory Keto service_version=v0.9.0-alpha.0
```
It seems like the "server_url" is parsed as an empty string. Because of that, the ory services don't send their own spans.
The ory services seem to correctly pick up the trace context from the incoming requests headers, but they don't send spans to the zipkin url. Example of this is in the picture
![image (2)](https://user-images.githubusercontent.com/67418286/185899945-7fd6a42f-c2aa-40af-a1d1-61e07beec94d.png)
.

### Reproducing the bug

Use the provided tracing config

### Relevant log output

```shell
09T13:10:12Z level=info msg=Zipkin tracer configured! Sending spans to  func=github.com/ory/x/logrusx.(*Logger).Logf file=/go/pkg/mod/github.com/ory/x@v0.0.451/logrusx/helper.go:118 audience=application service_name=Ory Keto service_version=v0.9.0-alpha.0
```

### Relevant configuration

```yml
tracing:
  service_name: Ory Keto
  providers:
    zipkin:
      server_url: http://tempo:9411/api/v2/spans
  provider: zipkin
```

### Version

0.0.451

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose
