### ISSUE TITLE
Allow to configure OTEL collector endpoint

### ISSUE THREAD

**Issue by omerlh** [ory/x#646]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/x/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/x/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Provide a way to configure the OTEL (for example, Jaeger) collector endpoint. Looking at the code, it seems that no configuration is passed so the library will use the default - which is localhost.

### Describe your ideal solution

A config option, like Jaeger or Zipkin, to specify the host and port.

### Workarounds or alternatives

Not that I am aware of.

### Version

latest

**Comment by bodymindarts** [comment]
Blocker for us too. Should be a small change as `otlptracehttp` package supports passing in an endpoint as an option https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp#Option.

**Comment by bodymindarts** [comment]
In latest release of oath keeper + kratos the following config worked:
```
      tracing:
        service_name: ${oathkeeper_tracing_service_name}
        provider: otel
        providers:
          otlp:
            server_url: ${jaeger_host}:4318
            insecure: true
```
