### ISSUE TITLE
Missing configuration for Jaeger

### ISSUE THREAD

**Issue by daviddelucca** [ory/x#655]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/x/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/x/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

It's missing some configuration for jaegerremote and traces are not being sent.

```
		jaegerRemoteSampler := jaegerremote.New(
			"jaegerremote",
			jaegerremote.WithSamplingServerURL(samplingServerURL),
		)
```

### Reproducing the bug

1. Use a docker-compose to run jaeger https://github.com/jaegertracing/jaeger/blob/main/examples/hotrod/docker-compose.yml
2. Clone repo https://github.com/ory/oathkeeper and use master branch
3. Add tracing with sampling to your configuration:
```
tracing:
  service_name: ory-oathkeeper
  provider: jaeger
  providers:
    jaeger:
      sampling:
        type: const
        server_url: http://127.0.0.1:5778/sampling
      local_agent_address: 127.0.0.1:6831
```
4. Execute some curls to oathkeeper as proxy
5. Check traces on jaeger

### Version

master

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None
